# Base image
FROM node:10.13-alpine as node

# Set working directory
WORKDIR /app

# Add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# Install and cache app dependencies
COPY package*.json /app/
RUN npm install

# Add app
COPY . /app

# Build app
RUN ng build --output-path=dist

FROM nginx:stable-alpine

COPY --from=node /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
